_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 5
                - 12
                - 53
                - 55
            "2":
                - 5
                - 12
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
data:
    value:
        dataset_path: ./data/lorenz.npz
        num_der: 2
        visible_vars:
            - 0
            - 1
loss:
    value:
        deriv_weight:
            - 1
            - 1
        reg_dzdt: 0
        reg_l1_sparse: 0
model:
    value:
        dt: 0.01
        hidden_size: 128
        pad: 4
        tmax: 100.02
optimizer:
    value:
        encoder:
            eps: 1e-16
            learning_rate: 0.001
            type: adabelief
        sym_model:
            eps: 1e-16
            learning_rate: 0.001
            type: adabelief
output:
    value:
        base_dir: ./runs/lorenz
training:
    value:
        early_stopping:
            enabled: true
            min_delta: 0.0001
            min_steps: 5000
            patience: 1000
        log_interval: 100
        n_steps: 1000
        save_interval: 1000
        sparse_interval: 5000
        sparse_thres: 0.001
wandb:
    value:
        entity: visriv
        name: null
        project: symrecon
