# Wandb configuration
wandb:
  project: "symrecon"
  entity: "visriv"  # Your personal account
  name: null  # Will be set automatically with timestamp

# Training configuration
training:
  n_steps: 10000
  log_interval: 1000
  save_interval: 1000
  sparse_thres: 1e-3
  sparse_interval: 5000
  early_stopping:
    enabled: True
    patience: 1000  # Number of steps to wait for improvement
    min_delta: 1e-4  # Minimum change to qualify as an improvement
    min_steps: 5000  # Minimum number of steps before early stopping can occur

# Model configuration
model:
  hidden_size: 128
  pad: 4
  dt: 1e-2
  tmax: 100.02

# Optimizer configuration
optimizer:
  encoder:
    type: "adabelief"
    learning_rate: 1e-3
    eps: 1e-16
  sym_model:
    type: "adabelief"
    learning_rate: 1e-3
    eps: 1e-16

# Loss function configuration
loss:
  deriv_weight: [1.0, 1.0]
  reg_dzdt: 0
  reg_l1_sparse: 0

# Data configuration
data:
  dataset_path: "./data/lorenz.npz"  # Path to save/load the dataset
  generate_if_not_exists: true  # Generate dataset if it doesn't exist
  version: "v1"  # Version tag for the dataset
  visible_vars: [0, 1, 2]  # Which variables to observe
  num_der: 2  # Number of derivatives to compute

# Output configuration
output:
  base_dir: "./runs/lorenz"

# Future configuration
future:
  init_mode: "last"  # or "custom"
  time_horizon: 5.0  # seconds to predict into future
  dt: 0.01          # time step for output points
  method: "RK45"    # integration method (RK45, RK23, DOP853, etc.)
  rtol: 1.0e-3      # relative tolerance
  atol: 1.0e-6      # absolute tolerance 